sudo: required
services:
  - docker

env:
  - NODE_VERSION=8-jessie

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-1.0
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-1.0

stages:
  - test
  - npm-targets

jobs:
  include:
    - stage: npm-targets
     name: "Test 8-Jessie"
     install: skip
     script:
     - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-1.0
     env:
     - NODE_VERSION=8-jessie
     - NPM_TARGET=test
